package repcheck.ingestion.common.placeholders

import java.time.Instant

import cats.effect.IO
import cats.effect.unsafe.implicits.global

import doobie.implicits._
import doobie.postgres.implicits._
import doobie.util.Write
import doobie.util.transactor.Transactor

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import repcheck.ingestion.common.db.TransactorResource
import repcheck.ingestion.common.testing.{DockerPostgresSpec, DockerRequired}
import repcheck.shared.models.congress.dos.member.MemberDO

class PlaceholderCreatorSpec extends AnyFlatSpec with Matchers with DockerPostgresSpec {

  private val creator = new DefaultPlaceholderCreator[IO]

  /**
   * Custom [[Write]] for [[MemberDO]] that omits `memberId` — the `id` column is auto-generated by the BIGSERIAL
   * sequence in the test schema. This produces 16 positional parameters matching the 16 non-PK columns in the INSERT.
   */
  private implicit val memberInsertWrite: Write[MemberDO] = {
    type Row = (
        String,
        Option[String],
        Option[String],
        Option[String],
        Option[String],
        Option[String],
        Option[String],
        Option[String],
        Option[String],
        Option[Int],
        Option[String],
        Option[String],
        Option[String],
        Option[String],
        Option[Instant],
        Option[Instant],
    )
    Write[Row].contramap[MemberDO] { m =>
      (
        m.naturalKey,
        m.firstName,
        m.lastName,
        m.directOrderName,
        m.invertedOrderName,
        m.honorificName,
        m.birthYear,
        m.currentParty,
        m.state,
        m.district,
        m.imageUrl,
        m.imageAttribution,
        m.officialUrl,
        m.updateDate,
        m.createdAt,
        m.updatedAt,
      )
    }
  }

  private val membersInsertSql: String =
    """INSERT INTO members (
      |  natural_key, first_name, last_name, direct_order_name, inverted_order_name,
      |  honorific_name, birth_year, current_party, state, district, image_url, image_attribution,
      |  official_url, update_date, created_at, updated_at
      |) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      |ON CONFLICT (natural_key) DO NOTHING""".stripMargin

  private def withRepo[A](
    block: (Transactor[IO], DoobieEntityRepository[IO, MemberDO]) => IO[A]
  ): A =
    TransactorResource
      .makeTransactor[IO](
        driverClassName = "org.postgresql.Driver",
        url = jdbcUrl,
        user = jdbcUser,
        pass = jdbcPassword,
        maxConnections = 4,
      )
      .use { xa =>
        val repo = new DoobieEntityRepository[IO, MemberDO](xa, membersInsertSql)
        sql"TRUNCATE TABLE members".update.run.transact(xa) >> block(xa, repo)
      }
      .unsafeRunSync()

  private def loadByKey(xa: Transactor[IO], key: String): IO[Option[MemberDO]] =
    sql"""SELECT id, natural_key, first_name, last_name, direct_order_name, inverted_order_name,
                 honorific_name, birth_year, current_party, state, district, image_url, image_attribution,
                 official_url, update_date, created_at, updated_at
          FROM members WHERE natural_key = $key"""
      .query[MemberDO]
      .option
      .transact(xa)

  private def countByKey(xa: Transactor[IO], key: String): IO[Int] =
    sql"SELECT COUNT(*) FROM members WHERE natural_key = $key".query[Int].unique.transact(xa)

  "PlaceholderCreator.ensureExists" should "insert a placeholder row when the entity is missing" taggedAs DockerRequired in {
    withRepo { (xa, repo) =>
      for {
        _      <- creator.ensureExists[MemberDO]("B000444", repo)
        loaded <- loadByKey(xa, "B000444")
      } yield {
        val member = loaded.getOrElse(fail("expected a row for B000444"))
        val _      = member.naturalKey shouldBe "B000444"
        val _      = member.firstName shouldBe None
        member.lastName shouldBe None
      }
    }
  }

  it should "be a no-op when the entity already exists (ON CONFLICT silently skips)" taggedAs DockerRequired in {
    withRepo { (xa, repo) =>
      for {
        _     <- creator.ensureExists[MemberDO]("B000444", repo)
        _     <- creator.ensureExists[MemberDO]("B000444", repo)
        count <- countByKey(xa, "B000444")
      } yield count shouldBe 1
    }
  }

  it should "be idempotent — calling twice leaves a single row" taggedAs DockerRequired in {
    withRepo { (xa, repo) =>
      for {
        _     <- creator.ensureExists[MemberDO]("S000148", repo)
        _     <- creator.ensureExists[MemberDO]("S000148", repo)
        count <- countByKey(xa, "S000148")
      } yield count shouldBe 1
    }
  }

  it should "create the placeholder with only the natural key populated" taggedAs DockerRequired in {
    withRepo { (xa, repo) =>
      for {
        _      <- creator.ensureExists[MemberDO]("S000148", repo)
        loaded <- loadByKey(xa, "S000148")
      } yield {
        val member = loaded.getOrElse(fail("expected a row for S000148"))
        val _      = member.naturalKey shouldBe "S000148"
        val _      = member.memberId should be > 0L
        val _      = member.firstName shouldBe None
        val _      = member.lastName shouldBe None
        val _      = member.directOrderName shouldBe None
        val _      = member.invertedOrderName shouldBe None
        val _      = member.honorificName shouldBe None
        val _      = member.birthYear shouldBe None
        val _      = member.currentParty shouldBe None
        val _      = member.state shouldBe None
        val _      = member.district shouldBe None
        val _      = member.imageUrl shouldBe None
        val _      = member.imageAttribution shouldBe None
        val _      = member.officialUrl shouldBe None
        val _      = member.updateDate shouldBe None
        val _      = member.createdAt shouldBe None
        member.updatedAt shouldBe None
      }
    }
  }

}
